### ISSUE TITLE
stem track list might better be a track dict

### ISSUE THREAD

**Issue by faroit** [marl/medleydb#10]
this way one could easily sort the stems or load specific stem tracks. Also that way special stems like the predominant just be pointer to the stems dict and wouldn't need to create a new object.

### Proposal

```mytrack.stems['1']```  should output stem_idx 1 as a track object.

using a list is prone to errors since ```mytrack.stems[1]``` does not necessarily exist.

**Comment by rabitt** [comment]
No argument here! +1

**Comment by rabitt** [comment]
This is done in the medleydb_v1.2 branch
