### ISSUE TITLE
medleydb version number

### ISSUE THREAD

**Issue by faroit** [marl/medleydb#16]
The repo tag indicate a ```1.0.0``` release of medleydb repo

The [python package](https://github.com/marl/medleydb/blob/master/setup.py#L7) however is still at version='0.1.0'

I would suggest bumping the version here as well

**Comment by faroit** [comment]
before things get more complicated with the recently added v.1.1.0 branch: can you sync the version tags with the package version number stated in the ```setup.py``` ? 

Ideally the tag for ```0.1.0``` would refer to the last known working version before you added the annotations: I guess this would be 82e103. That way people can more easily continue working with medleydb as described in the documentation.

**Comment by rabitt** [comment]
Ok, I've done some git hackery to get everything in order. Master is now at v0.2.0, matching the current setup.py. All of the changes past 82e103 previously in the master branch are now in a branch called medleydb_v1.0.0, which I'll merge with v1.1.0.

Not exactly what you suggested, but does this work for ya?
