### ISSUE TITLE
Stem Activations

### ISSUE THREAD

**Issue by faroit** [marl/medleydb#17]
Currently this package does not support to return the track activations. Is this of interest for you? I can implement this and send a PR.

**Comment by rabitt** [comment]
We have it implemented as Matlab code, and the author hasn't had a chance to clean it up to a releasable form. If you want to implement it in python that would be fantastic.

**Comment by faroit** [comment]
no worries. I can implement it, but I will wait until #15 is fixed, so that it will work on the 1.0 release as well

**Comment by faroit** [comment]
actually I need the activation annotation soon. So I would be happy If I can apply them on a stable master branch. What about putting your changes since 82e103 on the 1.0 or 1.1 branch?

**Comment by rabitt** [comment]
See my comment on #16
