### ISSUE TITLE
Bleed label issue

### ISSUE THREAD

**Issue by rabitt** [marl/medleydb#21]
(Thanks @lostanlen for noting this)

The following stems have bleed, but are not labeled as having bleed:

BrandonWebster_DontHearAThing_STEM_02.wav
ClaraBerryAndWooldog_Boys_STEM_05.wav
LizNelson_ImComingHome_STEM_02.wav

**Comment by lostanlen** [comment]
Hi,
Thank you for your reactivity.
Also, listening to
Lushlife_ToynbeeSuite_STEM_12.wav
you'll hear some faint, albeit noticeable, hi-hat sound over the guitar.
Yet the song is labeled has having no bleed.

**Comment by rabitt** [comment]
@lostanlen hmm I agree that Lushlife_ToynbeeSuite_STEM_12.wav has bleed. The rest of the stems for that multitrack don't (I don't think), and since I made ```has_bleed``` a multitrack level annotation, I'm hesitant to mark the whole thing as having bleed. 

Maybe, for the next version of the annotations, it would be reasonable to move ```has_bleed``` to the stem level instead of the track level. What do you think?

**Comment by lostanlen** [comment]
That is exactly my latest thought on the subject.
I use audio at the stem level for single-label instrument recognitiion, and must ensure that my stems have no bleed. That said, if there is bleed in another stem of the same track, but "my" stem is unaffected, it is too conservative to discard all stems altogether.
So having 'has_bleed' annotations at the stem level would definitely fit my use case.

**Comment by rabitt** [comment]
ok, I'm opening a separate issue to include this for v1.2.

**Comment by lostanlen** [comment]
I stumbled upon this bleed stem:
TheScarletBrand_LesFleursDuMal_STEM_08.wav

Again, other stems are not affected, which makes #27 all the more crucial.

**Comment by lostanlen** [comment]
I found two more bleeding stems:
ClaraBerryAndWooldog_Boys_STEM_01.wav
ClaraBerryAndWooldog_Boys_STEM_05.wav
The other 7 stems are not affected.

**Comment by carlthome** [comment]
CelestialShore_DireForUs vocals have bleed too.

**Comment by rabitt** [comment]
I created a log of each of these in [ERRATA.md](https://github.com/marl/medleydb/blob/medleydb_v1.2/ERRATA.md)
Closing this issue.
