### ISSUE TITLE
Non-alphanumerics in ACTIVATON_CONF file names

### ISSUE THREAD

**Issue by lostanlen** [marl/medleydb#22]
Hi,
Some instrument activation confidence file names — in Annotations/Instrument Activations/ACTIVATION_CONF — have discrepancies with the audio files they refer to. I think this is due to the presence of non-alphanumeric characters: parentheses, hyphens, and apostrophes.
Here is the list of before / after names.

CroqueMadame_Pilot(Lakelot)
CroqueMadame_Pilot

JoelHelander_IntheAtticBedroom(SuitePartThree)
JoelHelander_IntheAtticBedroom

Phoenix_BrokenPledge-ChicagoReel
Phoenix_BrokendPledge

Phoenix_Elzic'sFarewell
Phoenix_ElzicsFarewell

Phoenix_LarkOnTheStrand-DrummondCastle
Phoenix_LarkOnTheStrandDrummodCastle

Phoenix_SeanCaughlin's-TheScartaglan
Phoenix_SeanCaughlinsTheScartaglen

**Comment by rabitt** [comment]
@lostanlen I believe this should be fixed as of the v1.1 release in the Annotations directory of this repository. Can you confirm?

**Comment by lostanlen** [comment]
I'm the wrong person to ask, I'm no longer on the v1.1 branch.
