### ISSUE TITLE
Pandas dataframe for searching the database

### ISSUE THREAD

**Issue by rabitt** [marl/medleydb#23]
The sql submodule exists already, but this might be better suited within a pandas data frame.

**Comment by faroit** [comment]
Maybe [TinyDB](https://github.com/msiemens/tinydb) is worth a try?

**Comment by rabitt** [comment]
@faroit my thinking for pandas vs. a proper database is that it doesn't require create a separate db file. A data frame could filled similarly to the ```load_all_multitracks``` function.

**Comment by faroit** [comment]
Sure, I understand the benefit of this. But I guess pandas dataframes are not flexible enough for the many-to-many relationships of the medleydb resulting in nested lists/dicts...

**Comment by rabitt** [comment]
hmm I see your point. I think there are ways to have nested dataframes in pandas but as I recall it's a bit messy. If it's best to stick with a database, I think the current sqllite solution is fine.
