### ISSUE TITLE
Some raw tracks still have clearly audible effects processing applied

### ISSUE THREAD

**Issue by carlthome** [marl/medleydb#37]
`AClassicEducation_NightOwl_RAW_13_01.wav` and `AClassicEducation_NightOwl_RAW_13_02.wav` have some kind of modulation univibe-like effect applied to the vocals, and should not be considered raw.

I'm also guessing many raw tracks are dynamic range compressed and frequency equalized etc. (guessing artists tend to use channel-strips in their recording chain maybe) but that might be less of an issue in most applications. Are there any clear definitions on what constitutes a raw track in MedleyDB?

For reference, compare with `AClassicEducation_NightOwl_RAW_13_04.wav` which doesn't have the modulation effect.

**Comment by rabitt** [comment]
@carlthome: The raw tracks are not supposed to have any applied processing, including drc or equalization. The exception is anything affecting the time alignment (e.g. delays, "snap to grid", etc).

It will be an endeavor to go back and get the correct raw files for some of the multitracks. As a temporary fix, would it solve your use case to add a flag in the metadata that indicates there's a problem with a particular raw track? I'd initially set everything to false, but if we find a mistake for a particular track (as you have), we can flag it so you can remove it as needed.

**Comment by rabitt** [comment]
I added this to [ERRATA.md](https://github.com/marl/medleydb/blob/medleydb_v1.2/ERRATA.md)
Closing this issue.
