### ISSUE TITLE
Installing directly from git with pip places metadata and annotations directories incorrectly

### ISSUE THREAD

**Issue by carlthome** [marl/medleydb#39]
[The init script expects metadata to be placed in a repository root](https://github.com/marl/medleydb/blob/aca57be6c950f648b8b890202d39fc638e51226f/medleydb/__init__.py#L31), but if building with pip directly from git such as

`pip install git+git://github.com/marl/medleydb.git`

the directory structure becomes different and the MedleyDB Python tools won't work.

Since using pip with git is a fairly common way of installing from source it would be nice if the directory structure wasn't assumed. A neat and transparent fix would be to look for all resources (taxonomy.yaml, tracklist_v1.txt, Annotations/, Metadata/, etc.) in the MEDLEYDB_PATH as well, in the init script.

**Comment by rabitt** [comment]
I purposely want to keep the MEDLEYDB_PATH (i.e. the audio that is downloaded separately) functionally separate from the resources in the repository. The main reasons being:
- The audio is large and cannot be version controlled
- Because of the above point, I have found it more convenient to have the audio live in a separate folder from the repository folder.
- if the MEDLEYDB_PATH lives outside the repo folder, the install would have to copy the resources there, and upgrading new versions will be less clean.

That being said, I agree that the pip install should work :). Any idea of a way to do this while addressing the above points?

**Comment by carlthome** [comment]
This bug also happens when installing with `python setup.py install`. MedleyDB is looking for annotations in `'/home/carl/anaconda3/lib/python3.5/site-packages/medleydb/../Annotations'` which doesn't (and shouldn't) exist.

I think either `__init__.py` should look for metadata in `MEDLEYDB_PATH` as a fallback, or that `setup.py` should properly package the version controlled annotations and so on. This for example: http://stackoverflow.com/questions/1612733/including-non-python-files-with-setup-py

**Comment by mchijmma** [comment]
Hello,

I am not sure if this is the same bug, but I haven't being able to perform the installation. 

When I try `sudo python setup.py install` i get the following: 

> running install
running bdist_egg
running egg_info
writing requirements to medleydb.egg-info/requires.txt
writing medleydb.egg-info/PKG-INFO
writing top-level names to medleydb.egg-info/top_level.txt
writing dependency_links to medleydb.egg-info/dependency_links.txt
reading manifest file 'medleydb.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.rst'
warning: no files found matching '*.txt'
warning: no files found matching 'docs/Makefile'
warning: no files found matching '*.lab' under directory 'Annotations'
warning: no files found matching '*.txt' under directory 'Annotations'
warning: no files found matching '*.csv' under directory 'Annotations'
warning: no files found matching '*/*.csv' under directory 'Annotations'
warning: no files found matching '*.yaml' under directory 'METADATA'
no previously-included directories found matching 'docs/_build'
writing manifest file 'medleydb.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
installing package data to build/bdist.linux-x86_64/egg
running install_data
error: can't copy 'medleydb/data/Annotations': doesn't exist or not a regular file
> 

And when I try `sudo pip install git+git://github.com/marl/medleydb.git` : 

> Collecting git+git://github.com/marl/medleydb.git
  Cloning git://github.com/marl/medleydb.git to /tmp/pip-KBWmYd-build
Requirement already satisfied: sox in /usr/local/lib/python2.7/dist-packages (from medleydb==1.2.7)
Requirement already satisfied: pyyaml in /usr/lib/python2.7/dist-packages (from medleydb==1.2.7)
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from medleydb==1.2.7)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from medleydb==1.2.7)
Requirement already satisfied: librosa in /usr/local/lib/python2.7/dist-packages (from medleydb==1.2.7)
Requirement already satisfied: pydrive in /usr/local/lib/python2.7/dist-packages (from medleydb==1.2.7)
Requirement already satisfied: scipy in /usr/lib/python2.7/dist-packages (from medleydb==1.2.7)
Requirement already satisfied: audioread>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from librosa->medleydb==1.2.7)
Requirement already satisfied: scikit-learn>=0.14.0 in /usr/local/lib/python2.7/dist-packages (from librosa->medleydb==1.2.7)
Requirement already satisfied: matplotlib>=1.4.3 in /usr/lib/python2.7/dist-packages (from librosa->medleydb==1.2.7)
Requirement already satisfied: joblib>=0.7.0 in /usr/lib/python2.7/dist-packages (from librosa->medleydb==1.2.7)
Requirement already satisfied: decorator>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from librosa->medleydb==1.2.7)
Requirement already satisfied: resampy>=0.1.0 in /usr/local/lib/python2.7/dist-packages (from librosa->medleydb==1.2.7)
Requirement already satisfied: google-api-python-client>=1.2 in /usr/local/lib/python2.7/dist-packages (from pydrive->medleydb==1.2.7)
Requirement already satisfied: oauth2client>=4.0.0 in /usr/local/lib/python2.7/dist-packages (from pydrive->medleydb==1.2.7)
Requirement already satisfied: Cython>=0.23 in /usr/lib/python2.7/dist-packages (from resampy>=0.1.0->librosa->medleydb==1.2.7)
Requirement already satisfied: uritemplate<4dev,>=3.0.0 in /usr/local/lib/python2.7/dist-packages (from google-api-python-client>=1.2->pydrive->medleydb==1.2.7)
Requirement already satisfied: httplib2<1dev,>=0.9.2 in /usr/local/lib/python2.7/dist-packages/httplib2-0.9.2-py2.7.egg (from google-api-python-client>=1.2->pydrive->medleydb==1.2.7)
Requirement already satisfied: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0->pydrive->medleydb==1.2.7)
Requirement already satisfied: pyasn1-modules>=0.0.5 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0->pydrive->medleydb==1.2.7)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/lib/python2.7/dist-packages (from oauth2client>=4.0.0->pydrive->medleydb==1.2.7)
Installing collected packages: medleydb
  Running setup.py install for medleydb ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-KBWmYd-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-elA3pJ-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/medleydb
    copying medleydb/utils.py -> build/lib.linux-x86_64-2.7/medleydb
    copying medleydb/__init__.py -> build/lib.linux-x86_64-2.7/medleydb
    copying medleydb/mix.py -> build/lib.linux-x86_64-2.7/medleydb
    copying medleydb/version.py -> build/lib.linux-x86_64-2.7/medleydb
    copying medleydb/multitrack.py -> build/lib.linux-x86_64-2.7/medleydb
    copying medleydb/download.py -> build/lib.linux-x86_64-2.7/medleydb
    running install_lib
    creating /usr/local/lib/python2.7/dist-packages/medleydb
    copying build/lib.linux-x86_64-2.7/medleydb/utils.py -> /usr/local/lib/python2.7/dist-packages/medleydb
    copying build/lib.linux-x86_64-2.7/medleydb/__init__.py -> /usr/local/lib/python2.7/dist-packages/medleydb
    copying build/lib.linux-x86_64-2.7/medleydb/mix.py -> /usr/local/lib/python2.7/dist-packages/medleydb
    copying build/lib.linux-x86_64-2.7/medleydb/version.py -> /usr/local/lib/python2.7/dist-packages/medleydb
    copying build/lib.linux-x86_64-2.7/medleydb/multitrack.py -> /usr/local/lib/python2.7/dist-packages/medleydb
    copying build/lib.linux-x86_64-2.7/medleydb/download.py -> /usr/local/lib/python2.7/dist-packages/medleydb
    byte-compiling /usr/local/lib/python2.7/dist-packages/medleydb/utils.py to utils.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/medleydb/__init__.py to __init__.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/medleydb/mix.py to mix.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/medleydb/version.py to version.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/medleydb/multitrack.py to multitrack.pyc
    byte-compiling /usr/local/lib/python2.7/dist-packages/medleydb/download.py to download.pyc
    running install_data
    creating /usr/local/medleydb
    creating /usr/local/medleydb/resources
    copying medleydb/resources/artist_index.json -> /usr/local/medleydb/resources
    copying medleydb/resources/tracklist_v2.txt -> /usr/local/medleydb/resources
    copying medleydb/resources/pyin.n3 -> /usr/local/medleydb/resources
    copying medleydb/resources/tracklist_v1.txt -> /usr/local/medleydb/resources
    copying medleydb/resources/mixing_coefficients.yaml -> /usr/local/medleydb/resources
    copying medleydb/resources/tracklist_extra.txt -> /usr/local/medleydb/resources
    copying medleydb/resources/tracklist_bach10.txt -> /usr/local/medleydb/resources
    copying medleydb/resources/client_secrets.json -> /usr/local/medleydb/resources
    copying medleydb/resources/instrument_f0_type.json -> /usr/local/medleydb/resources
    copying medleydb/resources/taxonomy.yaml -> /usr/local/medleydb/resources
    creating /usr/local/medleydb/data
    error: can't copy 'medleydb/data/Annotations': doesn't exist or not a regular file
    

> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-KBWmYd-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-elA3pJ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-KBWmYd-build/



I already have this `export MEDLEYDB_PATH="/home/user/Music/MedleyDB"` in my .bashrc file


Then, I just try `import medleydb` and I get this:



> /usr/local/lib/python2.7/dist-packages/medleydb/__init__.py:28: UserWarning: The environment variable MEDLEYDB_PATH is not set. As a result, any part of the code that requires the audio won't work. If you don't need to access the audio, disregard this warning. If you do, set the environment variable MEDLEYDB_PATH to your local copy of MedleyDB.
>   UserWarning
> Traceback (most recent call last):
> 
>   File "<ipython-input-18-4380e0af57f1>", line 1, in <module>
>     import medleydb
> 
>   File "/usr/local/lib/python2.7/dist-packages/medleydb/__init__.py", line 57, in <module>
>     TRACK_LIST_V1 = read_tracklist('tracklist_v1.txt')
> 
>   File "/usr/local/lib/python2.7/dist-packages/medleydb/__init__.py", line 52, in read_tracklist
>     filename), 'r') as fhand:
> 
> IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/medleydb/resources/tracklist_v1.txt



Thanks in advance for your help.

**Comment by rabitt** [comment]
@mchijmma Try
```pip install -e .``` from the top level directory

My apologies for not updating the readme! Let me know if that works.

**Comment by mchijmma** [comment]
Hi, I did a new clean installation and it worked. Thanks!
