### ISSUE TITLE
Status on mixing tools?

### ISSUE THREAD

**Issue by carlthome** [marl/medleydb#43]
I've been rolling my own mixing code for MedleyDB but saw in https://github.com/marl/medleydb/pull/40 that there are branches with mixing functionality builtin that look very useful. What's the status on these? Could we expect the master branch to have these soon? https://github.com/marl/medleydb/tree/hanna/mix https://github.com/marl/medleydb/tree/mixing-tools

PS: It would be neat IMHO if master was https://github.com/marl/medleydb/tree/medleydb_v1.2 because it seems stable and also has Python 3 support.

**Comment by rabitt** [comment]
#40 has been merged to the medleydb_v1.2 branch.

Totally agree that medleydb_v1.2 needs to be merged to master. Working on that asap.
