### ISSUE TITLE
Raw track has bleed

### ISSUE THREAD

**Issue by TGabor** [marl/medleydb#46]
The meta data entry for Creepoid_OldTree_RAW says it has no bleed, but
Creepoid_OldTree_RAW_02_01.wav
contains bass and drums instead of bass only

**Comment by lostanlen** [comment]
Right now we cannot fix this because the has_bleed boolean is at the song level, and many other raw tracks from this song don't have bleed.
However, the situation may improve in future, with a finer grain of bleed vs. non-bleed annotations: see #21 and #27.

**Comment by rabitt** [comment]
I added this to [ERRATA.md](https://github.com/marl/medleydb/blob/medleydb_v1.2/ERRATA.md)
Closing this issue.
