### ISSUE TITLE
Download links to MedleyDB 2.0, where?

### ISSUE THREAD

**Issue by carlthome** [marl/medleydb#83]
The MedleyDB website makes no mention of the ISMIR 2016 paper yet, and the link in [the paper](https://wp.nyu.edu/ismir2016/wp-content/uploads/sites/2294/2016/08/bittner-medleydb.pdf) isn't working. I'm wondering where I can find the new MedleyDB 2.0 dataset?

I get that everyone has a lot on their plate which is great for MIR but I'd really like to hear the new tracks. :smile:

**Comment by ucasiggcas** [comment]
Dear,
I have the same question,Where is the MedleyDB dataset?
I say the wav or audio file.
Could U help me,Please?

**Comment by faroit** [comment]
Have a look here: https://zenodo.org/communities/sigsep/?page=1&size=20

**Comment by ucasiggcas** [comment]
> Have a look here: https://zenodo.org/communities/sigsep/?page=1&size=20
Thx at first
but,it was not what I want,
I want the dataset's direct download link,

**Comment by faroit** [comment]
As I understand: there is no direct download link and there never was. Please request access for the audio files on zenodo

**Comment by rabitt** [comment]
+1 to what @faroit said. You can find download links for MedleyDB and MedleyDB 2.0 on MedleyDB's [website](https://medleydb.weebly.com/downloads.html), which are both now hosted on Zenodo.

**Comment by jackwxs** [comment]
> +1 赞同[@faroit](https://github.com/faroit)[他说。您可以在 MedleyDB 的网站](https://medleydb.weebly.com/downloads.html)上找到 MedleyDB 和 MedleyDB 2.0 的下载链接，它们现在都托管在 Zenodo 上。

大家现在还有这个资源吗 作者应该是不维护了 申请好几个月没有响应，求分享资源
