### ISSUE TITLE
Missing data for version 2 of the dataset

### ISSUE THREAD

**Issue by shoegazerstella** [marl/medleydb#90]
Hi,
The [version 2](https://zenodo.org/record/1715175#.XPTaIdMzY_V) of the dataset contains 74 audio files, but only 23 of them have info about [activation](https://github.com/marl/medleydb/tree/master/medleydb/data/Annotations/Activation_Confidence). Am I looking in the wrong place?
Thanks a lot!

**Comment by kyungyunlee** [comment]
I also encountered many missing activation files and also many activation files missing corresponding audio files. I am also wondering if there is another place to obtain the dataset. 
Any help would be great :)

**Comment by kyungyunlee** [comment]
I contacted the author and got feedback. 
If there is a bleed in the audio, there is no activation annotation provided. 
And many of the audio in V2 are live recordings and have bleed so this is why :) 
Hope it helps someone in the future.
