### ISSUE TITLE
PyYAML yaml.load(input) Deprecation

### ISSUE THREAD

**Issue by beantowel** [marl/medleydb#91]
PyYAML5.1 has deprecated the old `yaml.load()` API. As the page [https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation](url) suggests, line
```
INST_TAXONOMY = yaml.load(fhandle)
MIXING_COEFFICIENTS = yaml.load(fhandle)
```
in medleydb's `__init__.py` would be better change into `yaml.load(input, Loader=yaml.FullLoader)` or something.

**Comment by migperfer** [comment]
Hi! Why was this marked as closed? 
There are many `yaml.load`  calls still [to be updated](https://github.com/search?q=repo%3Amarl%2Fmedleydb%20yaml.load&type=code), and the pull request that fixes one of them has not been merged
