### ISSUE TITLE
Download from zenodo fails

### ISSUE THREAD

**Issue by da-hon5** [marl/medleydb#97]
Hi, 
I have a problem with downloading the audio files from zenodo. After approximately 1 minute the download fails every time.

**Comment by da-hon5** [comment]
now it worked suddenly :)

**Comment by Cactooz** [comment]
@da-hon5, do you happen to still have access to the downloads on Zenodo? Would it be possible to get help downloading them? It seems no one has gotten download access for over 2 years now.
